title = "skarbek.name"
baseURL = "https://blog.skarbek.name/"
tags = ["containers", "linux", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "hugo-theme-slim"
canonifyURLS = true

[params]
  Subtitle = "Your site's subtitle/tagline"
  GithubID = "mskarbek"
  TwitterID = "marcinskarbek"
  #AnalyticsID = "Your Google Analytics tracking code"
  DisqusShortname = "Your Disqus shortname"
  Summary = true  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  FooterMsg = "Copyright Me 2018. Powered by Hugo."
