title = "skarbek.name"
baseURL = "https://blog.skarbek.name/"
tags = ["containers", "linux", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "hugo-theme-slim"
canonifyURLS = true

[taxonomies]
  tag = "tags"

[params]
  Subtitle = "suckin' at somethin' is the first step towards bein' sorta good at somethin'"
  GithubID = "mskarbek"
  TwitterID = "marcinskarbek"
  #AnalyticsID = "UA-46765415-1"
  DisqusShortname = "skarbek-name"
  Summary = true  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  FooterMsg = "Copyright Me 2018. Powered by Hugo."
